---
ci:
  autoupdate_schedule: monthly
  # format compatible with release-please
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  autofix_commit_msg: |
    chore: auto fixes from pre-commit.com hooks
    for more information, see https://pre-commit.ci
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: fix-byte-order-marker
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: debug-statements
        language_version: python3

  - repo: https://github.com/crate-ci/typos
    rev: v1.24.5
    hooks:
      - id: typos

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        exclude: ".ci/hack"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 'v0.6.3'
    hooks:
      - id: ruff
        args:
         - --fix
         - --exit-non-zero-on-fix

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.22
    hooks:
      - id: pymarkdown
        args:
          - -c
          - .pymarkdown.json
          - scan
        exclude: CHANGELOG.md # is autogenerated

  - repo: https://github.com/pycqa/pylint
    rev: v3.2.7
    hooks:
      - id: pylint
        pass_filenames: false
        entry: pylint lib tests
        args:
          - --output-format=colorized
        additional_dependencies:
          - .
          - ansible-core>=2.11.0
          - rich
          - pytest

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.4.10
    hooks:
      - id: uv-lock

      # as soon as https://github.com/astral-sh/uv-pre-commit/pull/18 gets merged, we can use the following hook
      # - id: uv-export
      #   args: ["--frozen", "--no-hashes", "-o=requirements-dev.txt"]
